name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore: 
      - '**.md' 
    
jobs:
#every job needs separate runner , it's called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      run: echo "code clone from github"
 
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container build"
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the Docker conatiner
        run: echo "Docker container build"
  
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: echo "docker compose deployed to server"
          
