---
name: Hello
on:
   workflow_dispatch: 
jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello to users
        run: echo "hello world"
      - name: say hello to username
        run: echo "hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of docker, python , etc
        run: docker --version && python --version 
      
